# Generated by Django 4.2.25 on 2025-10-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название коммерческого предложения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='draft', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='ImplementationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Этап реализации')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок этапа')),
            ],
            options={
                'verbose_name': 'Этап реализации',
                'verbose_name_plural': 'Этапы реализации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Подэтап реализации')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок подэтапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание подэтапа')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stages', to='generator.implementationstage', verbose_name='Этап реализации')),
            ],
            options={
                'verbose_name': 'Подэтап реализации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='generator.commercialproposal', verbose_name='Коммерческое предложение')),
            ],
            options={
                'verbose_name': 'Услуга',
            },
        ),
        migrations.AddField(
            model_name='implementationstage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='generator.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='generator.company', verbose_name='Компания'),
        ),
    ]
