# Generated by Django 4.2.25 on 2025-10-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.AlterModelOptions(
            name='commercialproposal',
            options={'verbose_name': 'Коммерческое предложение', 'verbose_name_plural': 'Коммерческие предложения'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='substage',
            options={'ordering': ['order'], 'verbose_name': 'Подэтап реализации', 'verbose_name_plural': 'Подэтапы реализации'},
        ),
        migrations.RemoveField(
            model_name='commercialproposal',
            name='status',
        ),
        migrations.AddField(
            model_name='substage',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Стоимость (₽)'),
        ),
        migrations.AddField(
            model_name='substage',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Продолжительность (дней)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='generator.project', verbose_name='Проект'),
        ),
    ]
