# Generated by Django 4.2.25 on 2025-10-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_project_alter_commercialproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substage',
            name='duration_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Продолжительность (дней)'),
        ),
    ]
