# Generated by Django 4.2.25 on 2025-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_substage_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='proposal',
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='generator.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
